// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXFZI_bqyz4rt1MMWFKEXALUZ9aYQA604',
    appId: '1:445796193532:web:f4f2d8508869029987f379',
    messagingSenderId: '445796193532',
    projectId: 'shopp-70b2f',
    authDomain: 'shopp-70b2f.firebaseapp.com',
    storageBucket: 'shopp-70b2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1e5cLfPVJ9jGTXcRl_JXxOY52zsvyJbQ',
    appId: '1:445796193532:android:588e8e4c9011405e87f379',
    messagingSenderId: '445796193532',
    projectId: 'shopp-70b2f',
    storageBucket: 'shopp-70b2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_bkVZx3J6Flg-C5Ql8GcqYurN5Loj0bI',
    appId: '1:445796193532:ios:851970f4d2b188ca87f379',
    messagingSenderId: '445796193532',
    projectId: 'shopp-70b2f',
    storageBucket: 'shopp-70b2f.appspot.com',
    iosClientId: '445796193532-o1c6a49rk5n7rb8iq8r6frtpeba9ehjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_bkVZx3J6Flg-C5Ql8GcqYurN5Loj0bI',
    appId: '1:445796193532:ios:0019bd7d2798d74287f379',
    messagingSenderId: '445796193532',
    projectId: 'shopp-70b2f',
    storageBucket: 'shopp-70b2f.appspot.com',
    iosClientId: '445796193532-dlrq03m3qjksshrrmkeovbjhuk41itok.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopp.RunnerTests',
  );
}
